/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 25
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 22
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 11
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_plain_text_token1 = 1,
  anon_sym_PERCENT = 2,
  anon_sym_RBRACK = 3,
  anon_sym_RPAREN = 4,
  anon_sym_RBRACE = 5,
  sym__newline = 6,
  sym__indent = 7,
  sym__dedent = 8,
  sym_string_start = 9,
  sym_string_content = 10,
  sym_string_end = 11,
  sym__comment = 12,
  sym__except = 13,
  sym_document = 14,
  sym__node = 15,
  sym_line = 16,
  sym_plain_text = 17,
  sym_tag = 18,
  sym_tag_name = 19,
  sym_block = 20,
  aux_sym_document_repeat1 = 21,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_plain_text_token1] = "plain_text_token1",
  [anon_sym_PERCENT] = "%",
  [anon_sym_RBRACK] = "]",
  [anon_sym_RPAREN] = ")",
  [anon_sym_RBRACE] = "}",
  [sym__newline] = "_newline",
  [sym__indent] = "_indent",
  [sym__dedent] = "_dedent",
  [sym_string_start] = "string_start",
  [sym_string_content] = "string_content",
  [sym_string_end] = "string_end",
  [sym__comment] = "_comment",
  [sym__except] = "_except",
  [sym_document] = "document",
  [sym__node] = "_node",
  [sym_line] = "line",
  [sym_plain_text] = "plain_text",
  [sym_tag] = "tag",
  [sym_tag_name] = "tag_name",
  [sym_block] = "block",
  [aux_sym_document_repeat1] = "document_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_plain_text_token1] = aux_sym_plain_text_token1,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym__newline] = sym__newline,
  [sym__indent] = sym__indent,
  [sym__dedent] = sym__dedent,
  [sym_string_start] = sym_string_start,
  [sym_string_content] = sym_string_content,
  [sym_string_end] = sym_string_end,
  [sym__comment] = sym__comment,
  [sym__except] = sym__except,
  [sym_document] = sym_document,
  [sym__node] = sym__node,
  [sym_line] = sym_line,
  [sym_plain_text] = sym_plain_text,
  [sym_tag] = sym_tag,
  [sym_tag_name] = sym_tag_name,
  [sym_block] = sym_block,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_plain_text_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__dedent] = {
    .visible = false,
    .named = true,
  },
  [sym_string_start] = {
    .visible = true,
    .named = true,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_string_end] = {
    .visible = true,
    .named = true,
  },
  [sym__comment] = {
    .visible = false,
    .named = true,
  },
  [sym__except] = {
    .visible = false,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_line] = {
    .visible = true,
    .named = true,
  },
  [sym_plain_text] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 3,
  [6] = 6,
  [7] = 6,
  [8] = 4,
  [9] = 9,
  [10] = 9,
  [11] = 11,
  [12] = 12,
  [13] = 12,
  [14] = 14,
  [15] = 11,
  [16] = 14,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 18,
  [24] = 19,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(1);
      if (lookahead == '%') ADVANCE(3);
      if (lookahead == ')') ADVANCE(5);
      if (lookahead == ']') ADVANCE(4);
      if (lookahead == '}') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(2);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(aux_sym_plain_text_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(2);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0, .external_lex_state = 2},
  [5] = {.lex_state = 0, .external_lex_state = 2},
  [6] = {.lex_state = 0, .external_lex_state = 2},
  [7] = {.lex_state = 0, .external_lex_state = 2},
  [8] = {.lex_state = 0, .external_lex_state = 2},
  [9] = {.lex_state = 0, .external_lex_state = 3},
  [10] = {.lex_state = 0, .external_lex_state = 4},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0, .external_lex_state = 2},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0, .external_lex_state = 2},
  [16] = {.lex_state = 0, .external_lex_state = 2},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0, .external_lex_state = 5},
  [19] = {.lex_state = 0, .external_lex_state = 5},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0, .external_lex_state = 5},
  [22] = {.lex_state = 0, .external_lex_state = 5},
  [23] = {.lex_state = 0, .external_lex_state = 5},
  [24] = {.lex_state = 0, .external_lex_state = 5},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_plain_text_token1] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
    [sym__dedent] = ACTIONS(1),
    [sym_string_start] = ACTIONS(1),
    [sym_string_content] = ACTIONS(1),
    [sym_string_end] = ACTIONS(1),
    [sym__comment] = ACTIONS(1),
    [sym__except] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(20),
    [sym__node] = STATE(2),
    [sym_line] = STATE(2),
    [sym_plain_text] = STATE(2),
    [sym_tag] = STATE(19),
    [sym_block] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_plain_text_token1] = ACTIONS(5),
    [anon_sym_PERCENT] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(5), 1,
      aux_sym_plain_text_token1,
    ACTIONS(7), 1,
      anon_sym_PERCENT,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    STATE(19), 1,
      sym_tag,
    STATE(3), 5,
      sym__node,
      sym_line,
      sym_plain_text,
      sym_block,
      aux_sym_document_repeat1,
  [20] = 5,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      aux_sym_plain_text_token1,
    ACTIONS(16), 1,
      anon_sym_PERCENT,
    STATE(19), 1,
      sym_tag,
    STATE(3), 5,
      sym__node,
      sym_line,
      sym_plain_text,
      sym_block,
      aux_sym_document_repeat1,
  [40] = 5,
    ACTIONS(7), 1,
      anon_sym_PERCENT,
    ACTIONS(19), 1,
      aux_sym_plain_text_token1,
    ACTIONS(21), 1,
      sym__dedent,
    STATE(24), 1,
      sym_tag,
    STATE(6), 5,
      sym__node,
      sym_line,
      sym_plain_text,
      sym_block,
      aux_sym_document_repeat1,
  [60] = 5,
    ACTIONS(11), 1,
      sym__dedent,
    ACTIONS(16), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      aux_sym_plain_text_token1,
    STATE(24), 1,
      sym_tag,
    STATE(5), 5,
      sym__node,
      sym_line,
      sym_plain_text,
      sym_block,
      aux_sym_document_repeat1,
  [80] = 5,
    ACTIONS(7), 1,
      anon_sym_PERCENT,
    ACTIONS(19), 1,
      aux_sym_plain_text_token1,
    ACTIONS(26), 1,
      sym__dedent,
    STATE(24), 1,
      sym_tag,
    STATE(5), 5,
      sym__node,
      sym_line,
      sym_plain_text,
      sym_block,
      aux_sym_document_repeat1,
  [100] = 5,
    ACTIONS(7), 1,
      anon_sym_PERCENT,
    ACTIONS(19), 1,
      aux_sym_plain_text_token1,
    ACTIONS(28), 1,
      sym__dedent,
    STATE(24), 1,
      sym_tag,
    STATE(5), 5,
      sym__node,
      sym_line,
      sym_plain_text,
      sym_block,
      aux_sym_document_repeat1,
  [120] = 5,
    ACTIONS(7), 1,
      anon_sym_PERCENT,
    ACTIONS(19), 1,
      aux_sym_plain_text_token1,
    ACTIONS(30), 1,
      sym__dedent,
    STATE(24), 1,
      sym_tag,
    STATE(7), 5,
      sym__node,
      sym_line,
      sym_plain_text,
      sym_block,
      aux_sym_document_repeat1,
  [140] = 2,
    ACTIONS(34), 1,
      sym__indent,
    ACTIONS(32), 3,
      ts_builtin_sym_end,
      aux_sym_plain_text_token1,
      anon_sym_PERCENT,
  [149] = 2,
    ACTIONS(36), 1,
      sym__indent,
    ACTIONS(32), 3,
      sym__dedent,
      aux_sym_plain_text_token1,
      anon_sym_PERCENT,
  [158] = 1,
    ACTIONS(38), 3,
      ts_builtin_sym_end,
      aux_sym_plain_text_token1,
      anon_sym_PERCENT,
  [164] = 1,
    ACTIONS(40), 3,
      ts_builtin_sym_end,
      aux_sym_plain_text_token1,
      anon_sym_PERCENT,
  [170] = 1,
    ACTIONS(40), 3,
      sym__dedent,
      aux_sym_plain_text_token1,
      anon_sym_PERCENT,
  [176] = 1,
    ACTIONS(42), 3,
      ts_builtin_sym_end,
      aux_sym_plain_text_token1,
      anon_sym_PERCENT,
  [182] = 1,
    ACTIONS(38), 3,
      sym__dedent,
      aux_sym_plain_text_token1,
      anon_sym_PERCENT,
  [188] = 1,
    ACTIONS(42), 3,
      sym__dedent,
      aux_sym_plain_text_token1,
      anon_sym_PERCENT,
  [194] = 2,
    ACTIONS(44), 1,
      aux_sym_plain_text_token1,
    STATE(22), 1,
      sym_tag_name,
  [201] = 1,
    ACTIONS(46), 1,
      sym__newline,
  [205] = 1,
    ACTIONS(48), 1,
      sym__newline,
  [209] = 1,
    ACTIONS(50), 1,
      ts_builtin_sym_end,
  [213] = 1,
    ACTIONS(52), 1,
      sym__newline,
  [217] = 1,
    ACTIONS(54), 1,
      sym__newline,
  [221] = 1,
    ACTIONS(56), 1,
      sym__newline,
  [225] = 1,
    ACTIONS(58), 1,
      sym__newline,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 20,
  [SMALL_STATE(4)] = 40,
  [SMALL_STATE(5)] = 60,
  [SMALL_STATE(6)] = 80,
  [SMALL_STATE(7)] = 100,
  [SMALL_STATE(8)] = 120,
  [SMALL_STATE(9)] = 140,
  [SMALL_STATE(10)] = 149,
  [SMALL_STATE(11)] = 158,
  [SMALL_STATE(12)] = 164,
  [SMALL_STATE(13)] = 170,
  [SMALL_STATE(14)] = 176,
  [SMALL_STATE(15)] = 182,
  [SMALL_STATE(16)] = 188,
  [SMALL_STATE(17)] = 194,
  [SMALL_STATE(18)] = 201,
  [SMALL_STATE(19)] = 205,
  [SMALL_STATE(20)] = 209,
  [SMALL_STATE(21)] = 213,
  [SMALL_STATE(22)] = 217,
  [SMALL_STATE(23)] = 221,
  [SMALL_STATE(24)] = 225,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [13] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [16] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 2, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plain_text, 2, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 5, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [50] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_name, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__newline = 0,
  ts_external_token__indent = 1,
  ts_external_token__dedent = 2,
  ts_external_token_string_start = 3,
  ts_external_token_string_content = 4,
  ts_external_token_string_end = 5,
  ts_external_token__comment = 6,
  ts_external_token_RBRACK = 7,
  ts_external_token_RPAREN = 8,
  ts_external_token_RBRACE = 9,
  ts_external_token__except = 10,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__newline] = sym__newline,
  [ts_external_token__indent] = sym__indent,
  [ts_external_token__dedent] = sym__dedent,
  [ts_external_token_string_start] = sym_string_start,
  [ts_external_token_string_content] = sym_string_content,
  [ts_external_token_string_end] = sym_string_end,
  [ts_external_token__comment] = sym__comment,
  [ts_external_token_RBRACK] = anon_sym_RBRACK,
  [ts_external_token_RPAREN] = anon_sym_RPAREN,
  [ts_external_token_RBRACE] = anon_sym_RBRACE,
  [ts_external_token__except] = sym__except,
};

static const bool ts_external_scanner_states[6][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__newline] = true,
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
    [ts_external_token_string_start] = true,
    [ts_external_token_string_content] = true,
    [ts_external_token_string_end] = true,
    [ts_external_token__comment] = true,
    [ts_external_token_RBRACK] = true,
    [ts_external_token_RPAREN] = true,
    [ts_external_token_RBRACE] = true,
    [ts_external_token__except] = true,
  },
  [2] = {
    [ts_external_token__dedent] = true,
  },
  [3] = {
    [ts_external_token__indent] = true,
  },
  [4] = {
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
  },
  [5] = {
    [ts_external_token__newline] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_haml_external_scanner_create(void);
void tree_sitter_haml_external_scanner_destroy(void *);
bool tree_sitter_haml_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_haml_external_scanner_serialize(void *, char *);
void tree_sitter_haml_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_haml(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_haml_external_scanner_create,
      tree_sitter_haml_external_scanner_destroy,
      tree_sitter_haml_external_scanner_scan,
      tree_sitter_haml_external_scanner_serialize,
      tree_sitter_haml_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "haml",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
